# Generated by Django 3.0.6 on 2020-06-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
