# Generated by Django 3.0.6 on 2020-06-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img1',
        ),
    ]
